// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updColMaxBy
NumericMatrix updColMaxBy(NumericMatrix mu, NumericMatrix fmax, IntegerVector fac, LogicalVector skip);
RcppExport SEXP _spotr_updColMaxBy(SEXP muSEXP, SEXP fmaxSEXP, SEXP facSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fmax(fmaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type fac(facSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type skip(skipSEXP);
    rcpp_result_gen = Rcpp::wrap(updColMaxBy(mu, fmax, fac, skip));
    return rcpp_result_gen;
END_RCPP
}
// updBaseMat
NumericMatrix updBaseMat(NumericMatrix bmat, NumericMatrix mu, NumericMatrix fmax, IntegerVector fac, NumericVector weights, LogicalVector skip);
RcppExport SEXP _spotr_updBaseMat(SEXP bmatSEXP, SEXP muSEXP, SEXP fmaxSEXP, SEXP facSEXP, SEXP weightsSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bmat(bmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fmax(fmaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type fac(facSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type skip(skipSEXP);
    rcpp_result_gen = Rcpp::wrap(updBaseMat(bmat, mu, fmax, fac, weights, skip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spotr_updColMaxBy", (DL_FUNC) &_spotr_updColMaxBy, 4},
    {"_spotr_updBaseMat", (DL_FUNC) &_spotr_updBaseMat, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_spotr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
