# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updColMaxBy <- function(mu, fmax, fac, skip) {
    .Call(`_spotr_updColMaxBy`, mu, fmax, fac, skip)
}

updBaseMat <- function(bmat, mu, fmax, fac, weights, skip) {
    .Call(`_spotr_updBaseMat`, bmat, mu, fmax, fac, weights, skip)
}

